### PR TITLE
Feat/relaxed reqs and conda package

### PR DESCRIPTION
**Pull request by MementoRC**
Relaxed the requirement. All tests pass with pydantic>2.x and other higher revision packages
   - Pydantic deprecated `dict()`, which was modified in the `test_msgs.py`
 
The framework for the Github/Actions conda package creation requires an `ANACONDA_TOKEN` to be created on anaconda.org and set as a `Secrets` in the repository
 
There is likely room for improvements. The primary goal is to relax the requirement for Hummingbot and move `commlib-py` into the conda package section and have more convenient conflict resolution for the environment

I ping'd you on Discord/hummingbot

### CODE REVIEW

**Comment by MementoRC** [comment]
@klpanagi @TheHolyRoger I created a conda-forge recipe at https://github.com/conda-forge/staged-recipes/pull/23774. Do you want to be added as maintainers?
This was one of my first recipe proposal, I may revisit it for improvements on what I learned since then. The recipe has not yet been reviewed by Conda-forge team

**Comment by klpanagi** [comment]
> Relaxed the requirement. All tests pass with pydantic>2.x and other higher revision packages
> 
>     * Pydantic deprecated `dict()`, which was modified in the `test_msgs.py`
> 
> 
> The framework for the Github/Actions conda package creation requires an `ANACONDA_TOKEN` to be created on anaconda.org and set as a `Secrets` in the repository
> 
> There is likely room for improvements. The primary goal is to relax the requirement for Hummingbot and move `commlib-py` into the conda package section and have more convenient conflict resolution for the environment
> 
> I ping'd you on Discord/hummingbot

Hello @MementoRC . Sorry, I was  "in muted" for some time due to some deadlines for my PhD.
I have performed some changes to the codebase since then. Can you revisit the PR. Changes were made to the dependencies and I just included your suggestions in the last commit.

Maybe remove the commit that changes the dependencies in `pyproject.toml` from the PR as I have included them.

Thank you for the contribution!! :metal:

**Comment by klpanagi** [comment]
> @klpanagi @TheHolyRoger I created a conda-forge recipe at [conda-forge/staged-recipes#23774](https://github.com/conda-forge/staged-recipes/pull/23774). Do you want to be added as maintainers? This was one of my first recipe proposal, I may revisit it for improvements on what I learned since then. The recipe has not yet been reviewed by Conda-forge team



> @klpanagi @TheHolyRoger I created a conda-forge recipe at [conda-forge/staged-recipes#23774](https://github.com/conda-forge/staged-recipes/pull/23774). Do you want to be added as maintainers? This was one of my first recipe proposal, I may revisit it for improvements on what I learned since then. The recipe has not yet been reviewed by Conda-forge team

Sure @MementoRC ! Thanks! :)
Awesome work!

**Comment by MementoRC** [comment]
@klpanagi Hey thanks and welcome back, we missed you on hummingbot! Well, sure I'll revisit it. I was hoping you would create a anaconda channel, so that hummingbot can 'trust' it, but the best approach is to upload to conda-forge, which diminishes the value-added of this PR anyway.

I hope you made good progress on your Ph.D

**Comment by MementoRC** [comment]
Forgot to close.

**Pull request closed without merging**
